### ISSUE TITLE
C.S.I. 2.6

### ISSUE THREAD

**Issue by MassyCare99** [italia/design-comuni-docs#46]
[C.SI](http://c.si/).2.6 - Valutazione dell’esperienza d’uso, chiarezza informativa della scheda di servizio
Il sito comunale permette la [valutazione della chiarezza informativa](https://docs.italia.it/italia/designers-italia/design-comuni-docs/it/versione-corrente/modello-sito-comunale/funzionalita.html#valutazione-della-chiarezza-informativa-delle-pagine) per ogni scheda di servizio, secondo le modalità indicate nella documentazione del modello di sito comunale.
Le valutazioni ottenute devono essere visualizzate back office dai vari impiegati oppure devono essere pubblici? Grazie

**Comment by danielenole** [comment]
Salve @MassyCare99, le valutazioni e i dati di feedback servono principalmente agli impiegati comunali per valutare l'efficacia informativa delle pagine ed eventuali modifiche. Non è necessario che le valutazioni siano visibili anche agli utenti
