### ISSUE TITLE
Sostituire Google Analytics con Web Analytics Italia

### ISSUE THREAD

**Issue by Shamar** [italia/design-comuni-docs#6]
Come ampiamente chiarito dal EDPS e dai Garanti della Privacy [Austriaco](https://www.dsb.gv.at/dam/jcr:c1eb937b-7527-450c-8771-74523b01223c/D155.027%20GA.pdf) e [Francese](https://www.cnil.fr/sites/default/files/atoms/files/decision_ordering_to_comply_anonymised_-_google_analytics.pdf), [non è possibile configurare Google Analytics in modo da garantire i diritti fondamentali dei cittadini europei](https://monitora-pa.it/2022/06/14/faq-cnil.html#06) e non è nemmeno possibile adottare, nei suoi riguardi [un approccio basato sul rischio](https://monitora-pa.it/2022/06/14/faq-cnil.html#13).
*(le [FAQ originali in francese sono disponibili qui](https://www.cnil.fr/en/use-google-analytics-and-data-transfers-united-states-cnil-orders-website-manageroperator-comply))*

E' dunque necessario rimuovere ogni riferimento a Google Analytics dalla documentazione di riferimento per la Pubblica Amministrazione Italiana.

**Comment by bfabio** [comment]
@Shamar @iusondemand thanks, fixed by #7
